/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists Layer 0 knowledge documents */
        get: operations["list_documents"];
        put?: never;
        /** @description Upload a new Layer 0 knowledge document (multipart/form-data) */
        post: operations["upload_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists keywords across the Context */
        get: operations["list_keywords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/keywords/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description HNSW vector search over keyword embeddings */
        post: operations["search_keywords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/keywords/{normalised}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets a keyword and its linked documents */
        get: operations["get_keyword"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/keywords/{normalised}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Co-occurring neighbourhood from one canonical keyword form */
        get: operations["related_keyword_http"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists typed knowledge rows */
        get: operations["list_knowledge_nodes_http"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/nodes/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Bulk UPSERT typed knowledge nodes and relates_to edges */
        post: operations["bulk_upsert_knowledge_nodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/nodes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Hybrid BM25 + HNSW search over typed knowledge nodes */
        post: operations["post_search_knowledge_nodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/nodes/{kind}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetches one typed knowledge node */
        get: operations["get_knowledge_node_http"];
        put?: never;
        post?: never;
        /** @description Deletes a typed knowledge row */
        delete: operations["delete_knowledge_node_http"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/nodes/{kind}/{slug}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Thin wrapper starting at one typed knowledge node */
        get: operations["related_knowledge_node_http"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Runs a top-k semantic query over the Layer 0 chunks */
        post: operations["query_knowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/traverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Depth-bounded walk over Layer 0 graph edges */
        post: operations["post_traverse_graph"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Gets a Layer 0 knowledge document by id */
        get: operations["get_document"];
        /** @description Replaces a Layer 0 knowledge document and re-runs its pipeline */
        put: operations["reprocess_document"];
        post?: never;
        /** @description Deletes a Layer 0 knowledge document */
        delete: operations["delete_document"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/{id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists chunks for a document */
        get: operations["list_chunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/{id}/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists keywords linked to a single document */
        get: operations["list_document_keywords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/{id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Streams the raw bytes of a document */
        get: operations["fetch_document_raw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{context_id}/knowledge/{id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Keywords and neighbours from a Layer 0 document id */
        get: operations["related_document_http"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Unified error response type for all REST endpoints. */
        ApiErrorResponse: {
            message: string;
        };
        ChunkJson: {
            /** Format: int64 */
            charEnd: number;
            /** Format: int64 */
            charStart: number;
            document: string;
            id: string;
            /** Format: int64 */
            position: number;
            section?: string | null;
            text: string;
            /** Format: int64 */
            tokenCount?: number | null;
        };
        ChunkPageJson: {
            chunks: components["schemas"]["ChunkJson"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        DocumentJson: {
            /** Format: int64 */
            chunkCount?: number | null;
            contentHash: string;
            /** Format: date-time */
            createdAt: string;
            error?: string | null;
            id: string;
            /** Format: int64 */
            keywordCount?: number | null;
            language?: string | null;
            mimeType: string;
            /** Format: date-time */
            processingCompletedAt?: string | null;
            /** Format: date-time */
            processingStartedAt?: string | null;
            /** Format: int64 */
            sizeBytes: number;
            source: string;
            status: string;
            title: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        DocumentKeywordJson: {
            id: string;
            normalised: string;
            /** Format: float */
            score: number;
            text: string;
        };
        DocumentKeywordsResponse: {
            keywords: components["schemas"]["DocumentKeywordJson"][];
        };
        DocumentPageJson: {
            documents: components["schemas"]["DocumentJson"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        GraphEvidenceJson: {
            edgeKind: string;
            neighbourLabel: string;
            /** Format: float */
            weight: number;
        };
        KeywordDetailJson: {
            /** Format: int64 */
            documentCount: number;
            documents: components["schemas"]["KeywordDocumentJson"][];
            id: string;
            normalised: string;
            text: string;
        };
        KeywordDocumentJson: {
            id: string;
            /** Format: float */
            score: number;
            title: string;
        };
        KeywordJson: {
            /** Format: int64 */
            documentCount: number;
            id: string;
            normalised: string;
            text: string;
        };
        KeywordPageJson: {
            keywords: components["schemas"]["KeywordJson"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        KeywordSearchHitJson: {
            /** Format: int64 */
            documentCount: number;
            id: string;
            normalised: string;
            /** Format: float */
            score: number;
            text: string;
        };
        KeywordSearchRequestJson: {
            /** Format: int32 */
            k?: number;
            query: string;
            /** Format: float */
            threshold?: number;
        };
        KeywordSearchResponseJson: {
            /** Format: int64 */
            queryMs: number;
            results: components["schemas"]["KeywordSearchHitJson"][];
        };
        /** @description Target endpoint for [`KnowledgeLinkUpsert`]. */
        KnowledgeLinkTarget: {
            /** @description Stable kind token (embedded in [`RecordId`]). */
            kind: string;
            /** @description Stable slug fragment (embedded in [`RecordId`]). */
            slug: string;
        };
        KnowledgeLinkUpsert: {
            label: string;
            /** @description Directed edge target `{ kind, slug }`. */
            to: components["schemas"]["KnowledgeLinkTarget"];
        };
        KnowledgeNodeFullJson: {
            content: unknown;
            /** Format: date-time */
            createdAt: string;
            embedding: number[];
            id: string;
            kind: string;
            scope: string[];
            sourceDocument?: string | null;
            title: string;
            /** Format: date-time */
            updatedAt: string;
        };
        KnowledgeNodeListedJson: {
            content: unknown;
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            scope: string[];
            sourceDocument?: string | null;
            title: string;
            /** Format: date-time */
            updatedAt: string;
        };
        KnowledgeNodePageJson: {
            nodes: components["schemas"]["KnowledgeNodeListedJson"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        KnowledgeNodeSearchHitJson: {
            node: components["schemas"]["KnowledgeSummaryJson"];
            /** Format: float */
            score: number;
        };
        KnowledgeNodeSearchRequest: {
            /** Format: int32 */
            k: number;
            kindFilter?: string | null;
            query: string;
            /** Format: int32 */
            rrfK?: number;
            /** Format: float */
            threshold: number;
            /** Format: float */
            vectorWeight?: number;
        };
        KnowledgeNodeSearchResponseJson: {
            /** Format: int64 */
            queryMs: number;
            results: components["schemas"]["KnowledgeNodeSearchHitJson"][];
        };
        /** @description One row from `POST /knowledge/nodes` bulk-upsert payloads. */
        KnowledgeNodeUpsertRow: {
            content?: unknown;
            kind: string;
            links?: components["schemas"]["KnowledgeLinkUpsert"][];
            slug: string;
            sourceDocument?: string | null;
            title: string;
        };
        KnowledgeSummaryJson: {
            id: string;
            kind: string;
            title: string;
        };
        QueryFilter: {
            documentIds?: string[];
            mimeType?: string[];
        };
        QueryHitChunkJson: {
            /** Format: int64 */
            charEnd: number;
            /** Format: int64 */
            charStart: number;
            document: string;
            id: string;
            /** Format: int64 */
            position: number;
            section?: string | null;
            text: string;
        };
        QueryHitDocumentJson: {
            id: string;
            source: string;
            title: string;
        };
        QueryHitJson: {
            chunk: components["schemas"]["QueryHitChunkJson"];
            document: components["schemas"]["QueryHitDocumentJson"];
            graphEvidence?: components["schemas"]["GraphEvidenceJson"][] | null;
            graphExpansion?: unknown;
            /** Format: float */
            score: number;
        };
        QueryRequestJson: {
            expandGraph?: boolean;
            filter?: null | components["schemas"]["QueryFilter"];
            /** Format: float */
            graphAlpha?: number;
            /** Format: int32 */
            graphDepth?: number;
            graphEdges?: string[];
            /** Format: int32 */
            k?: number;
            mode?: string;
            query: string;
            /** Format: float */
            rrfK?: number;
            /** Format: float */
            threshold?: number;
            /** Format: float */
            vectorWeight?: number;
        };
        QueryResponseJson: {
            /** Format: int64 */
            queryMs: number;
            results: components["schemas"]["QueryHitJson"][];
        };
        TraverseApiRequest: {
            direction?: string;
            edges: string[];
            labels?: string[];
            /** Format: int32 */
            limitPerHop?: number;
            /** Format: int32 */
            maxDepth?: number;
            /** Format: float */
            minScore?: number;
            start: components["schemas"]["TraverseStartJson"][];
        };
        TraverseApiResponse: {
            edges: components["schemas"]["TraverseEdgeJson"][];
            nodes: components["schemas"]["TraverseNodeJson"][];
        };
        TraverseEdgeJson: {
            from: string;
            kind: string;
            label?: string | null;
            /** Format: float */
            score?: number | null;
            to: string;
        };
        TraverseNodeJson: {
            /** Format: int32 */
            depth: number;
            id: string;
            kind?: string | null;
            normalised?: string | null;
            title?: string | null;
            type: string;
        };
        TraverseStartJson:
            | {
                  id: string;
                  /** @enum {string} */
                  type: "document";
              }
            | {
                  normalised: string;
                  /** @enum {string} */
                  type: "keyword";
              }
            | {
                  kind: string;
                  slug: string;
                  /** @enum {string} */
                  type: "knowledge";
              };
        UploadResponse: {
            contentHash: string;
            deduplicated: boolean;
            id: string;
            status: string;
        };
        Vec: components["schemas"]["KnowledgeNodeUpsertRow"][];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_documents: {
        parameters: {
            query?: {
                /** @description Filter by document status */
                status?: string;
                /** @description Filter by mime type */
                mime_type?: string;
                /** @description Page number (0-indexed) */
                page?: number;
                /** @description Page size, max 100 */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPageJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    upload_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Malformed multipart */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_keywords: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on text */
                q?: string;
                /** @description Minimum number of linked documents */
                minDocumentCount?: number;
                /** @description Sort key */
                sort?: string;
                /** @description Page number (0-indexed) */
                page?: number;
                /** @description Page size, max 100 */
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordPageJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    search_keywords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordSearchRequestJson"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordSearchResponseJson"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_keyword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Uppercase canonical keyword form */
                normalised: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordDetailJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Keyword not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    related_keyword_http: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
                normalised: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraverseApiResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_knowledge_nodes_http: {
        parameters: {
            query?: {
                kind?: string;
                q?: string;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodePageJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    bulk_upsert_knowledge_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vec"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    post_search_knowledge_nodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeNodeSearchRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeSearchResponseJson"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_knowledge_node_http: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
                kind: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeNodeFullJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete_knowledge_node_http: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
                kind: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    related_knowledge_node_http: {
        parameters: {
            query?: {
                label?: string;
                depth?: number;
            };
            header?: never;
            path: {
                context_id: string;
                kind: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraverseApiResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    query_knowledge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequestJson"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponseJson"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    post_traverse_graph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraverseApiRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraverseApiResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    reprocess_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Malformed multipart */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete_document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_chunks: {
        parameters: {
            query?: {
                /** @description Page number (0-indexed) */
                page?: number;
                /** @description Page size, max 100 */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPageJson"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_document_keywords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentKeywordsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    fetch_document_raw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Spectron context id */
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unexpected error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    related_document_http: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                context_id: string;
                /** @description Document id fragment */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraverseApiResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Invalid context id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
