name: 'Setup NPM for GitHub Package registry'
inputs:
  namespace:
    description: 'NPM namespace'
runs:
  using: "composite"
  steps:
    - name: Route namespace to GPR
      shell: 'bash'
      run: |
        echo >> $NPM_CONFIG_USERCONFIG
        echo '${{ inputs.namespace }}:registry=https://npm.pkg.github.com' >> $NPM_CONFIG_USERCONFIG
