name: 'Setup NPM for GitHub Package registry'
inputs:
  namespace:
    description: 'NPM namespace'
  githubToken:
    description: 'GitHub Token'
runs:
  using: "composite"
  steps:
    - name: Route namespace to GPR
      shell: 'bash'
      run: |
        echo '"//npm.pkg.github.com/:_authToken=${{ inputs.githubToken }}' >> .npmrc
        echo 'always-auth=true' >> .npmrc
        echo '${{ inputs.namespace }}:registry=https://npm.pkg.github.com' >> .npmrc
        echo PWD=$PWD
        cat .npmrc
        cat $NPM_CONFIG_USERCONFIG
