name: Publish release

on:
  release:
    types: [published]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read

  versions:
    name: Version check
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Compare versions
        run: bun run versions ${{ github.event.release.tag_name }}

  publish:
    name: Publish
    needs: [versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Configure publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Build
        run: bun run build

      - name: Validate publishing
        run: bun run publish all --dry-run

      - name: Publish to registries
        run: bun run publish all
