name: Publish

on:
    release:
        types: [published]

jobs:
    ci:
        name: CI
        uses: ./.github/workflows/ci.yml
    GPR:
        name: GPR
        needs: [ci]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Install Bun
              uses: oven-sh/setup-bun@v2

            - uses: actions/setup-node@v4
              with:
                node-version: '18.x'
                registry-url: 'https://registry.npmjs.org'

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: bun install

            - name: Build library
              run: bun run build

            - uses: ./.github/actions/configure-gpr-scope
              with:
                namespace: '@c0va23'
                githubToken: '${{ secrets.GITHUB_TOKEN }}'

            - name: Publish to NPM
              run: npm publish --provenance
