name: Publish

on:
  push:
    tags:
      - '*'

jobs:
    npm:
        name: NPM
        runs-on: ubuntu-latest
        steps:
            - name: Install Bun
              uses: oven-sh/setup-bun@v1

            - uses: actions/setup-node@v3
              with:
                node-version: '18.x'
                registry-url: 'https://registry.npmjs.org'

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: bun install

            - name: Build library
              run: bun run build

            - name: Publish to NPM
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    jsr:
        name: JSR
        runs-on: ubuntu-latest
        steps:
            - name: Install Bun
              uses: oven-sh/setup-bun@v1

            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: bun install

            - name: Generate JSR config
              run: bun run jsr

            - name: Publish to JSR
              run: bunx jsr publish
