name: Publish release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        surrealdb: ["v2.0.5", "v2.1.5", "v2.3.1"]
        engine: ["ws", "http"]
    steps:
      - name: Install SurrealDB ${{ matrix.surrealdb }} over ${{ matrix.engine }} engine
        run: curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh -s -- --version ${{ matrix.surrealdb }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
        env:
          SURREAL_DEFAULT_PROTOCOL: ${{ matrix.engine }}

  versions:
    name: Version check
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Compare versions
        run: bun run versions ${{ github.event.release.tag_name }}

  publish:
    name: Publish
    needs: [versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Validate publishing
        run: bun run publish all --dry-run
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to registries
        run: bun run publish all
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
