name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v3
      - run: deno task build
      # Publish with latest only versions that match the semver pattern, otherwise publish with beta tag
      # This is to avoid publishing beta versions with the latest tag (if no dist tag is provided, npm will use latest)
      - run: cd ./npm && npm publish --dist-tag $(npm pkg get version | tr -d '"' | grep -qoE "^\d+\.\d+\.\d+$" && echo 'latest' || echo 'beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
